//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sunctum.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sunctum.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   About Sunctum に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AboutSunctumDialogTitle {
            get {
                return ResourceManager.GetString("AboutSunctumDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Saved Dir に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BookProeprtyDialog_SavedDir {
            get {
                return ResourceManager.GetString("BookProeprtyDialog_SavedDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Author に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BookPropertyDialog_Author {
            get {
                return ResourceManager.GetString("BookPropertyDialog_Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Author Management... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BookPropertyDialog_AuthorManagement {
            get {
                return ResourceManager.GetString("BookPropertyDialog_AuthorManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Book ID に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BookPropertyDialog_BookID {
            get {
                return ResourceManager.GetString("BookPropertyDialog_BookID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Publish Date に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BookPropertyDialog_PublishDate {
            get {
                return ResourceManager.GetString("BookPropertyDialog_PublishDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open in Explorer に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BookPropertyDialog_SavedDir_Tooltip {
            get {
                return ResourceManager.GetString("BookPropertyDialog_SavedDir_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Size に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BookPropertyDialog_Size {
            get {
                return ResourceManager.GetString("BookPropertyDialog_Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Title に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BookPropertyDialog_Title {
            get {
                return ResourceManager.GetString("BookPropertyDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Total Page Count に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BookPropertyDialog_TotalPageCount {
            get {
                return ResourceManager.GetString("BookPropertyDialog_TotalPageCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Property of [{0}]{1} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BookPropertyDialogTitle {
            get {
                return ResourceManager.GetString("BookPropertyDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Common_Add {
            get {
                return ResourceManager.GetString("Common_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cancel に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Common_Cancel {
            get {
                return ResourceManager.GetString("Common_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Close に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Common_Close {
            get {
                return ResourceManager.GetString("Common_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ↓ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Common_Down {
            get {
                return ResourceManager.GetString("Common_Down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Edit に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Common_Edit {
            get {
                return ResourceManager.GetString("Common_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Next &gt;&gt; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Common_Next {
            get {
                return ResourceManager.GetString("Common_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OK に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Common_Ok {
            get {
                return ResourceManager.GetString("Common_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;&lt; _Prev に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Common_Previous {
            get {
                return ResourceManager.GetString("Common_Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Remove に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Common_Remove {
            get {
                return ResourceManager.GetString("Common_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ↑ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Common_Up {
            get {
                return ResourceManager.GetString("Common_Up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pattern に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EditMetadataImportSettingDialog_Pattern {
            get {
                return ResourceManager.GetString("EditMetadataImportSettingDialog_Pattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open details in browser に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EditMetadataImportSettingDialog_Pattern_Tooltip {
            get {
                return ResourceManager.GetString("EditMetadataImportSettingDialog_Pattern_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   https://docs.microsoft.com/en-us/dotnet/standard/base-types/regular-expression-language-quick-reference に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EditMetadataImportSettingDialog_PatternUri {
            get {
                return ResourceManager.GetString("EditMetadataImportSettingDialog_PatternUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add pattern に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EditMetadataImportSettingDialogTitle_Add {
            get {
                return ResourceManager.GetString("EditMetadataImportSettingDialogTitle_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Edit pattern に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EditMetadataImportSettingDialogTitle_Edit {
            get {
                return ResourceManager.GetString("EditMetadataImportSettingDialogTitle_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Details に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ErrorReportDialog_Details {
            get {
                return ResourceManager.GetString("ErrorReportDialog_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   I&apos;m sorry に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ErrorReportDialog_ImSorry {
            get {
                return ResourceManager.GetString("ErrorReportDialog_ImSorry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sunctum will be terminated, because Unexpected ERROR occured. You can see the details of exception by press に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ErrorReportDialog_Message_1st {
            get {
                return ResourceManager.GetString("ErrorReportDialog_Message_1st", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [Details] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ErrorReportDialog_Message_2nd {
            get {
                return ResourceManager.GetString("ErrorReportDialog_Message_2nd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   button on bottom of this dialog. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ErrorReportDialog_Message_3rd {
            get {
                return ResourceManager.GetString("ErrorReportDialog_Message_3rd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sunctum ERROR Report に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ErrorReportDialogTitle {
            get {
                return ResourceManager.GetString("ErrorReportDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Exporting destination に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ExportDialog_ExportDestination {
            get {
                return ResourceManager.GetString("ExportDialog_ExportDestination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Include tags to export files and folders に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ExportDialog_IncludeTagToExportingFilesAndFolders {
            get {
                return ResourceManager.GetString("ExportDialog_IncludeTagToExportingFilesAndFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Option に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ExportDialog_Option {
            get {
                return ResourceManager.GetString("ExportDialog_Option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Export に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ExportDialogTitle {
            get {
                return ResourceManager.GetString("ExportDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _DATA に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainWindow_Data {
            get {
                return ResourceManager.GetString("MainWindow_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Author Management... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainWindow_Data_AuthorManagement {
            get {
                return ResourceManager.GetString("MainWindow_Data_AuthorManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Book Size に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainWindow_Data_BookSize {
            get {
                return ResourceManager.GetString("MainWindow_Data_BookSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Update Size all books に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainWindow_Data_BookSize_UpdateSizeAllBooks {
            get {
                return ResourceManager.GetString("MainWindow_Data_BookSize_UpdateSizeAllBooks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Update Size quickly に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainWindow_Data_BookSize_UpdateSizeQuickly {
            get {
                return ResourceManager.GetString("MainWindow_Data_BookSize_UpdateSizeQuickly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Book-tag に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainWindow_Data_BookTag {
            get {
                return ResourceManager.GetString("MainWindow_Data_BookTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Update book-tag all に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainWindow_Data_BookTag_UpdateBookTagAll {
            get {
                return ResourceManager.GetString("MainWindow_Data_BookTag_UpdateBookTagAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Encryption start... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainWindow_Data_EncryptionStart {
            get {
                return ResourceManager.GetString("MainWindow_Data_EncryptionStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Metadata Import setting... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainWindow_Data_MetadataImportSetting {
            get {
                return ResourceManager.GetString("MainWindow_Data_MetadataImportSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tag Management... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainWindow_Data_TagManagement {
            get {
                return ResourceManager.GetString("MainWindow_Data_TagManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unencryption start... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainWindow_Data_UnencryptionStart {
            get {
                return ResourceManager.GetString("MainWindow_Data_UnencryptionStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _DISPLAY に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainWindow_Display {
            get {
                return ResourceManager.GetString("MainWindow_Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Showcase に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainWindow_Display_DisplayType {
            get {
                return ResourceManager.GetString("MainWindow_Display_DisplayType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Details に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainWindow_Display_DisplayType_Details {
            get {
                return ResourceManager.GetString("MainWindow_Display_DisplayType_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SideBySide に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainWindow_Display_DisplayType_SideBySide {
            get {
                return ResourceManager.GetString("MainWindow_Display_DisplayType_SideBySide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sorting に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainWindow_Display_Sorting {
            get {
                return ResourceManager.GetString("MainWindow_Display_Sorting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   By Author Asc に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainWindow_Display_Sorting_AuthorAsc {
            get {
                return ResourceManager.GetString("MainWindow_Display_Sorting_AuthorAsc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   By Author Desc に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainWindow_Display_Sorting_AuthorDesc {
            get {
                return ResourceManager.GetString("MainWindow_Display_Sorting_AuthorDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   By Cover Blue Asc に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainWindow_Display_Sorting_CoverBlueAsc {
            get {
                return ResourceManager.GetString("MainWindow_Display_Sorting_CoverBlueAsc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   By Cover Blue Desc に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainWindow_Display_Sorting_CoverBlueDesc {
            get {
                return ResourceManager.GetString("MainWindow_Display_Sorting_CoverBlueDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   By Cover Green Asc に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainWindow_Display_Sorting_CoverGreenAsc {
            get {
                return ResourceManager.GetString("MainWindow_Display_Sorting_CoverGreenAsc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   By Cover Green Desc に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainWindow_Display_Sorting_CoverGreenDesc {
            get {
                return ResourceManager.GetString("MainWindow_Display_Sorting_CoverGreenDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   By Cover Red Asc に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainWindow_Display_Sorting_CoverRedAsc {
            get {
                return ResourceManager.GetString("MainWindow_Display_Sorting_CoverRedAsc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   By Cover Red Desc に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainWindow_Display_Sorting_CoverRedDesc {
            get {
                return ResourceManager.GetString("MainWindow_Display_Sorting_CoverRedDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   By FingerPrint Asc に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainWindow_Display_Sorting_FingerPrintAsc {
            get {
                return ResourceManager.GetString("MainWindow_Display_Sorting_FingerPrintAsc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   By FingerPrint Desc に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainWindow_Display_Sorting_FingerPrintDesc {
            get {
                return ResourceManager.GetString("MainWindow_Display_Sorting_FingerPrintDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   By loaded ASC に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainWindow_Display_Sorting_LoadedAsc {
            get {
                return ResourceManager.GetString("MainWindow_Display_Sorting_LoadedAsc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   By loaded DESC に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainWindow_Display_Sorting_LoadedDesc {
            get {
                return ResourceManager.GetString("MainWindow_Display_Sorting_LoadedDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   By Title Asc に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainWindow_Display_Sorting_TitleAsc {
            get {
                return ResourceManager.GetString("MainWindow_Display_Sorting_TitleAsc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   By Title Desc に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainWindow_Display_Sorting_TitleDesc {
            get {
                return ResourceManager.GetString("MainWindow_Display_Sorting_TitleDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Window に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainWindow_Display_Window {
            get {
                return ResourceManager.GetString("MainWindow_Display_Window", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Author に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainWindow_Display_Window_Author {
            get {
                return ResourceManager.GetString("MainWindow_Display_Window_Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Information に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainWindow_Display_Window_Information {
            get {
                return ResourceManager.GetString("MainWindow_Display_Window_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tag に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainWindow_Display_Window_Tag {
            get {
                return ResourceManager.GetString("MainWindow_Display_Window_Tag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _FILE に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainWindow_File {
            get {
                return ResourceManager.GetString("MainWindow_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Exit Sunctum に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainWindow_File_ExitSunctum {
            get {
                return ResourceManager.GetString("MainWindow_File_ExitSunctum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Import Files... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainWindow_File_ImportFiles {
            get {
                return ResourceManager.GetString("MainWindow_File_ImportFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Import Folders... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainWindow_File_ImportFolders {
            get {
                return ResourceManager.GetString("MainWindow_File_ImportFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Import Library... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainWindow_File_ImportLibrary {
            get {
                return ResourceManager.GetString("MainWindow_File_ImportLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Preferences... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainWindow_File_Preferences {
            get {
                return ResourceManager.GetString("MainWindow_File_Preferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recent Libraries に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainWindow_File_RecentLibraries {
            get {
                return ResourceManager.GetString("MainWindow_File_RecentLibraries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Reload Library に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainWindow_File_ReloadLibrary {
            get {
                return ResourceManager.GetString("MainWindow_File_ReloadLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Switch Library... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainWindow_File_SwitchLibrary {
            get {
                return ResourceManager.GetString("MainWindow_File_SwitchLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _HELP に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainWindow_Help {
            get {
                return ResourceManager.GetString("MainWindow_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   About Sunctum... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainWindow_Help_AboutSunctum {
            get {
                return ResourceManager.GetString("MainWindow_Help_AboutSunctum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Update Sunctum... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainWindow_Help_UpdateApp {
            get {
                return ResourceManager.GetString("MainWindow_Help_UpdateApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _SEARCH に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainWindow_Search {
            get {
                return ResourceManager.GetString("MainWindow_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Clear Search Result に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainWindow_Search_ClearSearchResult {
            get {
                return ResourceManager.GetString("MainWindow_Search_ClearSearchResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainWindow_Search_Search {
            get {
                return ResourceManager.GetString("MainWindow_Search_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pattern に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MetadataImportSettingDialog_Pattern {
            get {
                return ResourceManager.GetString("MetadataImportSettingDialog_Pattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Priority に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MetadataImportSettingDialog_Priority {
            get {
                return ResourceManager.GetString("MetadataImportSettingDialog_Priority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Metadata import setting に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MetadataImportSettingDialogTitle {
            get {
                return ResourceManager.GetString("MetadataImportSettingDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   General に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PreferencesDialog_General {
            get {
                return ResourceManager.GetString("PreferencesDialog_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Connection string に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PreferencesDialog_General_ConnectionString {
            get {
                return ResourceManager.GetString("PreferencesDialog_General_ConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Generate thumbnail in multithread に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PreferencesDialog_General_GenerateThumbnailInMultithread {
            get {
                return ResourceManager.GetString("PreferencesDialog_General_GenerateThumbnailInMultithread", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Lock importing file に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PreferencesDialog_General_LockImportingFile {
            get {
                return ResourceManager.GetString("PreferencesDialog_General_LockImportingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Maximum number of libraries opened recently に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PreferencesDialog_General_MaximumNumberOfLibrariesRecentlyOpened {
            get {
                return ResourceManager.GetString("PreferencesDialog_General_MaximumNumberOfLibrariesRecentlyOpened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Quality of thumbnail に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PreferencesDialog_General_QualityOfThumbnail {
            get {
                return ResourceManager.GetString("PreferencesDialog_General_QualityOfThumbnail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save window position に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PreferencesDialog_General_SaveWindowPosition {
            get {
                return ResourceManager.GetString("PreferencesDialog_General_SaveWindowPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Working directory に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PreferencesDialog_General_WorkingDirectory {
            get {
                return ResourceManager.GetString("PreferencesDialog_General_WorkingDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Layout に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PreferencesDialog_Layout {
            get {
                return ResourceManager.GetString("PreferencesDialog_Layout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Author に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PreferencesDialog_Layout_Author {
            get {
                return ResourceManager.GetString("PreferencesDialog_Layout_Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Author Height に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PreferencesDialog_Layout_AuthorHeight {
            get {
                return ResourceManager.GetString("PreferencesDialog_Layout_AuthorHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Book ListViewItem に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PreferencesDialog_Layout_BookListViewItem {
            get {
                return ResourceManager.GetString("PreferencesDialog_Layout_BookListViewItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Content ListViewItem に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PreferencesDialog_Layout_ContentListViewItem {
            get {
                return ResourceManager.GetString("PreferencesDialog_Layout_ContentListViewItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Image に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PreferencesDialog_Layout_Image {
            get {
                return ResourceManager.GetString("PreferencesDialog_Layout_Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Image Height に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PreferencesDialog_Layout_ImageHeight {
            get {
                return ResourceManager.GetString("PreferencesDialog_Layout_ImageHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ListViewItem MarginBottom に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PreferencesDialog_Layout_ListViewItem_MarginBottom {
            get {
                return ResourceManager.GetString("PreferencesDialog_Layout_ListViewItem_MarginBottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ListViewItem MarginLeft に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PreferencesDialog_Layout_ListViewItem_MarginLeft {
            get {
                return ResourceManager.GetString("PreferencesDialog_Layout_ListViewItem_MarginLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ListViewItem MarginRight に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PreferencesDialog_Layout_ListViewItem_MarginRight {
            get {
                return ResourceManager.GetString("PreferencesDialog_Layout_ListViewItem_MarginRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ListViewItem MarginTop に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PreferencesDialog_Layout_ListViewItem_MarginTop {
            get {
                return ResourceManager.GetString("PreferencesDialog_Layout_ListViewItem_MarginTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ListViewItem Width に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PreferencesDialog_Layout_ListViewItem_Width {
            get {
                return ResourceManager.GetString("PreferencesDialog_Layout_ListViewItem_Width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Preview に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PreferencesDialog_Layout_Preview {
            get {
                return ResourceManager.GetString("PreferencesDialog_Layout_Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Title に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PreferencesDialog_Layout_Title {
            get {
                return ResourceManager.GetString("PreferencesDialog_Layout_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Title Height に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PreferencesDialog_Layout_TitleHeight {
            get {
                return ResourceManager.GetString("PreferencesDialog_Layout_TitleHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Preferences に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PreferencesDialogTitle {
            get {
                return ResourceManager.GetString("PreferencesDialogTitle", resourceCulture);
            }
        }
    }
}
